### ISSUE TITLE
Add photos of the Symposium somewhere on the website

### ISSUE THREAD

**Issue by calejvaldez** [ojosproject/website#33]
### Summary

We managed to take great photos at the symposium, and I think we should add them somewhere. Potentially on an "About" page?

### Concept images and/or code

[Internal Google Drive folder with the pictures](https://drive.google.com/drive/folders/12m_Vo5XeYGjv0yok0-WHEYNAUgJUr7bz).

**Comment by Electric108** [comment]
I agree with your comment. Generating a gallery showing us doing daily work would be beneficial and could achieve this effect.
 I am attaching some files from our [UROP PHOTOS](https://drive.google.com/drive/folders/12m_Vo5XeYGjv0yok0-WHEYNAUgJUr7bz) that I think are good for this below:
![20240517_141206](https://github.com/ojosproject/website/assets/106860652/7f4b7d63-3831-4b22-a295-4214c6d4b3cf)
![20240517_141724](https://github.com/ojosproject/website/assets/106860652/282b79e5-9339-4ca3-83cd-c3a62dc77118)
![20240517_143002](https://github.com/ojosproject/website/assets/106860652/e1492a74-0c43-4e57-82aa-50cc4da57d5d)
![20240517_143010](https://github.com/ojosproject/website/assets/106860652/e5a8963d-5aff-41c9-bcd9-fbc29b3785fb)
![20240517_151120](https://github.com/ojosproject/website/assets/106860652/9910cca5-9d4a-43e4-bd80-e9e27f26e8d9)
![20240517_151123](https://github.com/ojosproject/website/assets/106860652/eb7b7c49-bff5-4ef0-96f1-93398e487b66)

**Comment by calejvaldez** [comment]
Finally, an update: this is being worked on in #51 where we talk about research.
