### ISSUE TITLE
Update the 2024 Symposium New with edits 

### ISSUE THREAD

**Issue by Electric108** [ojosproject/website#34]
### Summary

The current symposium's new release is good.; however, more information and visuals on the event will be beneficial.

These include:
- dive deeper into why we did the background of the Symposium e.g to promote our research, gather feedback, interact with peers, network with professionals
- Include more details on the members attending
- proof-reading its writing
- Include testimonials from the members
- adding a gallery of the photos rather than giving the public access 
- The event needs to be expanded by, as previously mentioned, by including a review or assessment on the event. 
- Reference the Symposium supplemental material we generated. E.g a digital version of the poster rather than a second-hand picture, a pdf of our reference materials, and potentially a folder for our STL files of published iterations of Palliview. 

### Reasoning

These suggestions will help answer potential questions and clarify some intentions. Additionally, it will show opportunities for growth and development of the Team. 

Furthermore, some issues such as the public access to the drive raise problems with the privacy of the members and allow us to select an adequate amount of voice in what information is allow to be published. for

**Comment by Electric108** [comment]
here is one of the reference material mentioned above of the virtual poster.
[2024 Symposium Poster.pdf](https://github.com/ojosproject/website/files/15429401/2024.Symposium.Poster.pdf)

**Comment by calejvaldez** [comment]
PR #35 created, you're good to go

**Comment by calejvaldez** [comment]
> Furthermore, some issues such as the public access to the drive raise problems with the privacy of the members and allow us to select an adequate amount of voice in what information is allow to be published. for

Drive folder set to Restricted mode for internal use only. Almost everything in the Ojos Project will be public unless someone has a concern, which will then be set to internal use only.

**Comment by Electric108** [comment]
Everything except pictures we added
