### ISSUE TITLE
Updated Summer research News.

### ISSUE THREAD

**Issue by Electric108** [ojosproject/website#46]
### Summary

Previously, the LAEP had been discontinued but with some help from our financial aid representatives,
![Screenshot 2024-07-12 214408](https://github.com/user-attachments/assets/3546dd8c-94ab-4847-a08f-86974ba116f6)
 they were able to ensure that this year will be funded despite the legislation being cut. 

### Type of Docs Issue

Docs is outdated

**Comment by calejvaldez** [comment]
Fixed in d7b7c2a9bfc9fae90d855017b63fb3a87d4f7d4e. Just removed the original update
