### ISSUE TITLE
count down for the chi competition cpplication submission

### ISSUE THREAD

**Issue by Electric108** [ojosproject/website#57]
### Summary

A countdown linking the [Student Research Competition submission](https://chi2025.acm.org/for-authors/student-research-competition/) would be beneficial in keeping the supporters and project members updated on the goals.

It is set for Thursday, Jan 23rd, AoE. it can be adjusted for the PST the Ojos project was based on.  This is similar to this [website](https://dateful.com/convert/aoe-anywhere-on-earth?t=1007am&d=2025-01-23).

### Concept images and/or code

'''

**Comment by calejvaldez** [comment]
Added in 0a8f912a82c40fb3a98cab3f6a6903e1c9c02031
